export enum EggGroup {
  BUG = 'bug',
  DITTO = 'ditto',
  DRAGON = 'dragon',
  FAIRY = 'fairy',
  FIELD = 'field',
  FLYING = 'flying',
  GRASS = 'grass',
  HUMAN_LIKE = 'human_like',
  AMORPHOUS = 'amorphous',
  MINERAL = 'mineral',
  MONSTER = 'monster',
  WATER1 = 'water1',
  WATER2 = 'water2',
  WATER3 = 'water3',
  CANNOT_BREED = 'cannot_breed',
}
